image: python:3.9

stages:
  - lint
  - test

# Variables for the test environment. With DATABASE_URL empty,
# your code will use SQLite (local development mode).
variables:
  FLASK_ENV: testing
  DATABASE_URL: ""

cache:
  paths:
    - .cache/pip

before_script:
  - pip install -r requirements.txt

lint:
  stage: lint
  script:
    - pip install flake8
    - flake8 .

test:
  stage: test
  script:
    - pip install pytest
    - pytest --maxfail=1 --disable-warnings -q
